spring.application.name=BookHub_API
spring.datasource.url=${BDD_URL}
spring.datasource.username=${BDD_USERNAME}
spring.datasource.password=${BDD_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Détail des requêtes pour le développement
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.sql.init.mode=always

# Activer/désactiver Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Chemin de la documentation
springdoc.swagger-ui.path=/swagger-ui.html

# Version de l'API
springdoc.api-docs.version=openapi_3_0

# Paquet à scanner pour les contrôleurs
springdoc.packages-to-scan=com.ton.package

# Configuration JWT permettant de vérifier de signer et vérifier le token
jwt.secret=superSecretKeyChangeMe_superSecretKeyChangeMe_123456
